In [1]:
import pandas as pd

In [2]:
# read data using pandas
train_df = pd.read_csv('/Users/kavya/Documents/Python_datascience/keras/data/hourly_wages_data.csv')

In [3]:
# check if the data has read properly
train_df.head()

wage_per_hour  union  education_yrs  experience_yrs  age  female  marr  \
0           5.10      0              8              21   35       1     1   
1           4.95      0              9              42   57       1     1   
2           6.67      0             12               1   19       0     0   
3           4.00      0             12               4   22       0     0   
4           7.50      0             12              17   35       0     1   

   south  manufacturing  construction  
0      0              1             0  
1      0              1             0  
2      0              1             0  
3      0              0             0  
4      0              0             0

In [4]:
#create a dataframe with all training data except the target column
train_X = train_df.drop(['wage_per_hour'],axis=1)
# check that the target variable has been removed
train_X.head()

union  education_yrs  experience_yrs  age  female  marr  south  \
0      0              8              21   35       1     1      0   
1      0              9              42   57       1     1      0   
2      0             12               1   19       0     0      0   
3      0             12               4   22       0     0      0   
4      0             12              17   35       0     1      0   

   manufacturing  construction  
0              1             0  
1              1             0  
2              1             0  
3              0             0  
4              0             0

In [5]:
# create a dataframe with only one target variable
train_y = train_df[['wage_per_hour']]
# view dataframe
train_y.head()

wage_per_hour
0           5.10
1           4.95
2           6.67
3           4.00
4           7.50

In [6]:
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
from keras.callbacks import EarlyStopping
# create model
model = Sequential()
# get number of columns in training data
n_cols = train_X.shape[1]
#add model layers
model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
model.add(Dense(10, activation='relu'))
model.add(Dense(1))

Using TensorFlow backend.


In [7]:
#compile model using mse as a measure of model performance
model.compile(optimizer='adam', loss='mean_squared_error')

In [8]:
from keras.callbacks import EarlyStopping
#set early stopping monitor so the model stops training when it won't improve anymore
early_stopping_monitor = EarlyStopping(patience=3)
#train model
model.fit(train_X, train_y, validation_split=0.2, epochs=30, callbacks=[early_stopping_monitor])

Train on 427 samples, validate on 107 samples
Epoch 1/30
427/427 [==============================] - 1s 2ms/step - loss: 124.0376 - val_loss: 174.0251
Epoch 2/30
427/427 [==============================] - 0s 74us/step - loss: 88.1379 - val_loss: 133.9320
Epoch 3/30
427/427 [==============================] - 0s 74us/step - loss: 58.3028 - val_loss: 97.1907
Epoch 4/30
427/427 [==============================] - 0s 69us/step - loss: 38.1802 - val_loss: 70.8461
Epoch 5/30
427/427 [==============================] - 0s 62us/step - loss: 29.2727 - val_loss: 54.8130
Epoch 6/30
427/427 [==============================] - 0s 67us/step - loss: 26.2115 - val_loss: 48.5717
Epoch 7/30
427/427 [==============================] - 0s 59us/step - loss: 25.4061 - val_loss: 46.5937
Epoch 8/30
427/427 [==============================] - 0s 52us/step - loss: 24.8049 - val_loss: 45.2923
Epoch 9/30
427/427 [==============================] - 0s 56us/step - loss: 24.1786 - val_loss: 44.3471
Epoch 10/30
427/427 [====

In [9]:
#creating new input test data 
test_X = pd.DataFrame({'union' : [0,0],'education_yrs' : [8,9],'experience_yrs' : [21,42],'age' : [35,57],'female' : [1,1],'marr' : [1,1],'south' : [0,0],'manufaturing' : [1,1],'construction' : [0,0]})
test_X

union  education_yrs  experience_yrs  age  female  marr  south  \
0      0              8              21   35       1     1      0   
1      0              9              42   57       1     1      0   

   manufaturing  construction  
0             1             0  
1             1             0

In [10]:
# testing the model with the new data
test_y_predictions = model.predict(test_X)
test_y_predictions

array([[6.6682982],
       [6.95249  ]], dtype=float32)

In [11]:
#training a new model on the same data to show the effect of increasing model capacity

#create model
model_mc = Sequential()

#add model layers
model_mc.add(Dense(200, activation='relu', input_shape=(n_cols,)))
model_mc.add(Dense(200, activation='relu'))
model_mc.add(Dense(200, activation='relu'))
model_mc.add(Dense(1))

#compile model using mse as a measure of model performance
model_mc.compile(optimizer='adam', loss='mean_squared_error')

In [12]:
#train model
model_mc.fit(train_X, train_y, validation_split=0.2, epochs=30, callbacks=[early_stopping_monitor])

Train on 427 samples, validate on 107 samples
Epoch 1/30
427/427 [==============================] - 1s 2ms/step - loss: 37.3628 - val_loss: 56.7024
Epoch 2/30
427/427 [==============================] - 0s 147us/step - loss: 22.8273 - val_loss: 37.5878
Epoch 3/30
427/427 [==============================] - 0s 131us/step - loss: 20.5814 - val_loss: 27.9140
Epoch 4/30
427/427 [==============================] - 0s 125us/step - loss: 20.8157 - val_loss: 28.4232
Epoch 5/30
427/427 [==============================] - 0s 127us/step - loss: 20.1589 - val_loss: 29.7356
Epoch 6/30
427/427 [==============================] - 0s 122us/step - loss: 20.3556 - val_loss: 36.2918


In [13]:
#creating new input test data for model 2 
test_X1 = pd.DataFrame({'union' : [0,0],'education_yrs' : [8,9],'experience_yrs' : [21,42],'age' : [35,57],'female' : [1,1],'marr' : [1,1],'south' : [0,0],'manufaturing' : [1,1],'construction' : [0,0]})
test_X1

union  education_yrs  experience_yrs  age  female  marr  south  \
0      0              8              21   35       1     1      0   
1      0              9              42   57       1     1      0   

   manufaturing  construction  
0             1             0  
1             1             0

In [14]:
# testing the model_2 with the new data
test_y1_predictions = model_mc.predict(test_X1)
test_y1_predictions

array([[5.5185237],
       [6.2071323]], dtype=float32)

In [15]:
#read in training data
train_df_2 = pd.read_csv('/Users/kavya/Documents/Python_datascience/keras/data/diabetes_data.csv')

#view data structure
train_df_2.head()

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0            6      148         72       35        0  33.6  0.627   50   
1            1       85         66       29        0  26.6  0.351   31   
2            8      183         64        0        0  23.3  0.672   32   
3            1       89         66       23       94  28.1  0.167   21   
4            0      137         40       35      168  43.1  2.288   33   

   diabetes  
0         1  
1         0  
2         1  
3         0  
4         1

In [16]:
#create a dataframe with all training data except the target column
train_X_2 = train_df_2.drop(['diabetes'],axis='columns')

#check that the target variable has been removed
train_X_2.head()

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age
0            6      148         72       35        0  33.6  0.627   50
1            1       85         66       29        0  26.6  0.351   31
2            8      183         64        0        0  23.3  0.672   32
3            1       89         66       23       94  28.1  0.167   21
4            0      137         40       35      168  43.1  2.288   33

In [17]:
#one-hot encode target column
train_y_2 = to_categorical(train_df_2.diabetes)

#vcheck that target column has been converted
train_y_2[0:5]

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]], dtype=float32)

In [18]:
import tensorflow as tf
tf.__version__

'1.9.0'

In [19]:
#create model
model_2 = Sequential()

#get number of columns in training data
n_cols_2 = train_X_2.shape[1]

#add layers to model
model_2.add(Dense(250, activation='relu', input_shape=(n_cols_2,)))
model_2.add(Dense(250, activation='relu'))
model_2.add(Dense(250, activation='relu'))
model_2.add(Dense(2, activation='softmax'))

#compile model using accuracy to measure model performance
model_2.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [22]:
#train model
model_2.fit(train_X_2, train_y_2, epochs=30, validation_split=0.2, callbacks=[early_stopping_monitor])

Train on 614 samples, validate on 154 samples
Epoch 1/30
614/614 [==============================] - 1s 2ms/step - loss: 5.3280 - acc: 0.6531 - val_loss: 5.7565 - val_acc: 0.6429
Epoch 2/30
614/614 [==============================] - 0s 159us/step - loss: 5.5934 - acc: 0.6498 - val_loss: 5.7565 - val_acc: 0.6429
Epoch 3/30
614/614 [==============================] - 0s 172us/step - loss: 5.5438 - acc: 0.6531 - val_loss: 5.7565 - val_acc: 0.6429
Epoch 4/30
614/614 [==============================] - 0s 171us/step - loss: 5.5598 - acc: 0.6515 - val_loss: 5.7565 - val_acc: 0.6429


In [23]:
#creating new input test data for model 2 
test_X_2 = pd.DataFrame({'pregnancies' : [6,1],'glucose' : [148,85],'diastolic' : [72,66],'triceps' : [35,29],'insulin' : [0,0],'bmi' : [33.6,26.6],'dpf' : [0.627,0.351],'age' : [50,31]})
test_X_2

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age
0            6      148         72       35        0  33.6  0.627   50
1            1       85         66       29        0  26.6  0.351   31

In [24]:
#test the model with the new input test data
test_y_2_predictions = model_2.predict(test_X_2)
test_y_2_predictions

array([[1.0000000e+00, 5.0477597e-33],
       [1.0000000e+00, 1.3896102e-19]], dtype=float32)